name: 'Setup QMK Vial firmware'

inputs:
  version:
    default: 'dev/ble-micro-pro'
    type: string
    required: false
  path:
    default: '__qmk_vial__'
    type: string
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout vial-qmk
    uses: actions/checkout@v4
    with:
      path: ${{ inputs.path }}
      repository: sekigon-gonnoc/vial-qmk
      submodules: recursive
      ref: ${{ inputs.version }}

  - name: Install git and pip
    shell: bash
    run: sudo apt-get install -y git python3-pip

  - name: Install QMK CLI
    shell: bash
    run: python3 -m pip install --user qmk

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes
