name: Keyball61 firmware

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

permissions:
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup QMK firmware
      uses: ./.github/actions/setup-qmk

    - name: Install a link to own source
      run: ln -s $(pwd)/qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - run: make -j4 SKIP_GIT=yes keyball/keyball61:default:uf2
      working-directory: __qmk__

    - run: make -j4 SKIP_GIT=yes keyball/keyball61:test:uf2
      working-directory: __qmk__

    - run: make -j4 SKIP_GIT=yes keyball/keyball61:bmp:uf2
      working-directory: __qmk__

    - name: Archive firmwares
      uses: actions/upload-artifact@v3
      with:
        name: keyball61-firmwares
        path: |
          __qmk__/*.uf2

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')

    steps:
    - name: Download built firmwares
      uses: actions/download-artifact@v3
      with:
        name: keyball61-firmwares
    - name: List assets
      run: ls -l *.uf2
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
        files: |
          *.uf2
        fail_on_unmatched_files: true
        generate_release_notes: true
        append_body: true
